liip_imagine:
    driver: "gd"

    filter_sets:

        thumb:
            quality: 100
            filters:
                thumbnail:
                    size: [300, 225]
                    mode: inset

        mini_thumb:
            quality: 100
            filters:
                thumbnail:
                    size: [80, 80]
                    mode: inset

        large:
            quality: 100
            filters:
                thumbnail:
                    size: [500, 400]
                    mode: inset
