tetranz_select2_entity:
  minimum_input_length: 0
  page_limit: 8
  allow_clear: true
  delay: 500
  language: 'fr'
  theme: 'default'
  cache: false
  cache_timeout: 0
  scroll: true
  render_html: true