twig:
    globals:
        twigClinic: '@App\Service\Clinic\ClinicServices'
        twigSettings: '@App\Service\Settings\SettingServices'

    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: [
            'bootstrap_4_layout.html.twig',
            '@TetranzSelect2Entity/Form/fields.html.twig',
            '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    ]