vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        photos:
            uri_prefix: /images/photos
            upload_destination: '%kernel.project_dir%/public/images/photos'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        cvs:
            uri_prefix: /images/cv
            upload_destination: '%kernel.project_dir%/public/images/cv'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
